### ISSUE TITLE
deploy does'nt work find: zimbra-zimlet-rocketchat-main.xml not found 

### ISSUE THREAD

**Issue by laurent6** [Zimbra/zimbra-zimlet-rocketchat#1]
When I deploy  zimlet I have this following error: 

```
[zimbra@t-zimmbx01 ~]$  zmzimletctl deploy zimbra-zimlet-rocketchat-main.zip
java.io.FileNotFoundException: zimlet description not found: zimbra-zimlet-rocketchat-main.xml
	at com.zimbra.cs.zimlet.ZimletFile.initZimletDescription(ZimletFile.java:267)
	at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:223)
	at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:175)
	at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:156)
	at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1910)
	at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2012)
[] ERROR: Error
java.io.FileNotFoundException: zimlet description not found: zimbra-zimlet-rocketchat-main.xml
	at com.zimbra.cs.zimlet.ZimletFile.initZimletDescription(ZimletFile.java:267)
	at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:223)
	at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:175)
	at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:156)
	at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1910)
	at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2012)
```
what's wrong ?

**Comment by laurent6** [comment]
My mistake I use zimbra 9 instead of zimbra 8
